### ISSUE TITLE
Minimum Kodi Version

### ISSUE THREAD

**Issue by ReDrUm** [Wimpie-ccc/script.service.bluray_iso_utils#3]
Hi,
What's the minimum Kodi version required by this plugin? I've attempted to use it with 14.2 but no luck. Presumably 15 or 16+?
Cheers.

**Comment by Wimpie-ccc** [comment]
You need minimum Kodi 17.

**Comment by ReDrUm** [comment]
Ok thanks. Is this defined in any of the plugin manifest files? How do you usually figure it out?

**Comment by Wimpie-ccc** [comment]
I added this in the wiki.

Also, this addon is stil a work in progress. The service portion is more or less 'stable', but I'm making a GUI at the moment for building the BIUinfo.xml files (not yet available, is in alpha state).
